default:
  image: ruby:2.7
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - cache/bundler/
  before_script:
    - apt-get update
    - apt-get install -y sqlite3 libsqlite3-dev nodejs
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=cache/bundler

stages:
  - build
  - deploy

install-and-build:
  stage: build
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - cache/bundler/
  script:
    - cache/bundler/ruby/2.7.0/bin/jekyll b
  artifacts:
    name: "deployable"
    expire_in: "1 day"
    paths:
      - _deploy/

deploy:
  image: 
    name: amazon/aws-cli:2.0.50
    entrypoint: [""]
  before_script:
    - ''
  stage: deploy
  script:
    #- ls _deploy/
    - aws s3 sync _deploy/ s3://tmp-tiagoespinha.net/ --region eu-west-2 --delete
  dependencies:
    - install-and-build
