default:
  image: ruby:2.7
  before_script:
    - apt-get update
    - apt-get install -y sqlite3 libsqlite3-dev nodejs
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}"

stages:
  - build
  - deploy

install-and-build:
  stage: build
  script:
    - jekyll b
  artifacts:
    name: "deployable"
    expire_in: "1 day"
    paths:
      - _deploy/

deploy:
  image: amazon/aws-cli:2.0.50
  stage: deploy
  script:
    #- ls _deploy/
    - s3 sync /mnt/to-sync/ s3://tmp-tiagoespinha.net/ --region eu-west-2 --delete
  dependencies:
    - install-and-build
