default:
  image: ruby:2.7
  before_script:
    - apt-get update
    - apt-get install -y sqlite3 libsqlite3-dev nodejs
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}"

stages:
  - build
  - deploy

install-and-build:
  stage: build
  script:
    - jekyll b
  artifacts:
    name: "deployable"
    expire_in: "1 day"
    paths:
      - _deploy/

deploy:
  stage: deploy
  script:
    - ls _deploy/
  dependencies:
    - install-and-build
