title: "Tiago's Tech Blog"
description: My Personal Blog
author: Tiago Espinha
#logo: https://www.tiagoespinha.net/static/img/avatar.png
github: https://github.com/etiago
about: "Tiago's Tech Blog"
destination: _deploy
disqus_shortname: tiagostechblog
google_analytics: UA-5075580-2
exclude: [cache]
header_pages:
  - about.md
  - projects.md
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Resume
      url: '#'
      icon: fa-graduation-cap
    - text: GitHub
      url: https://github.com/etiago
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
      
social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'
    - icon: fa-stack-exchange
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "https://www.tiagoespinha.net"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
theme: minimal-mistakes-jekyll
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
minimal_mistakes_skin: "dirt"
